#IMPORTANT: between the Request Information and the actual query: one line needs to be kept free
@baseUrl = https://eu-artifactory.jfrog.tech
@accessToken = eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJ0eUxrUkhOTGwwQlNHclVOaUZ1bDg0YWlyNWhBMnlXNjRTOTVuYVNia2s0In0.eyJleHQiOiJ7XCJyZXZvY2FibGVcIjpcInRydWVcIn0iLCJzdWIiOiJqZmFjQDAxZnJqdDdqd2YxYW1hMWRzMWF0N20wcm5xXC91c2Vyc1wvZnZqLWFkbSIsInNjcCI6ImFwcGxpZWQtcGVybWlzc2lvbnNcL2FkbWluIiwiYXVkIjoiKkAqIiwiaXNzIjoiamZmZUAwMDAiLCJleHAiOjE2NzQxMjA1OTAsImlhdCI6MTY0MjU4NDU5MCwianRpIjoiZGY5MDRkMzEtZjQzZC00YzZkLTlmZDktN2FhZWMzY2U5YWExIn0.Ujx9SNeiu8ZQnTiroSRM_zHxbUNQBlxNhNX1mbKQet9DXxNcURMkOskQFJ3G7CZp_5sY4rnir9i9WuLCEEhhID00HecP1s9QED4ahwg648GgR8otMRbecL2231HWNyJRRdvt9jE0Z3euCkI8s3kQMp-n_eHC7bRSbHGvhe89RVvZKwU3kqTcrB1VjSzy0-ZhNDCRm3jvynSnEEBwZpGHLTlv9yJMj4Km-5EF_lPYs35zABNBklWXRfM12lV7Ou-geMoUKohz1ixVHCyaBxT95Hcyu-GSEyEGgjflUYvWSxEpbFrzWfZr7wuwsOQqa99xCTKKYYUIreZ3nO8KAJlmVw

@projectKey = fd-101
@repoTech = npm
@repoMaturity = dev
@repoLocator = remote
@repoUrl = https://registry.npmjs.org
@repoUsr = fjagwitz
@repoToken = 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
@repoInternalDescription = Frontend-Application
@repoPublicDescription = This Repo is managed within the Project: 

PUT {{baseUrl}}/artifactory/api/repositories/{{projectKey}}-{{repoTech}}-{{repoMaturity}}-{{repoLocator}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
"key": "{{projectKey}}-{{repoTech}}-{{repoMaturity}}-{{repoLocator}}",
"projectKey" : "{{projectKey}}",
"environments" : ["DEV", "PROD"],
"rclass" : "{{repoLocator}}",
"packageType": "{{repoTech}}",
"url" : "{{repoUrl}}",
"username" : "{{repoUsr}}",
"password" : "{{repoToken}}",
"externalDependenciesEnabled": false,
"description": "{{repoPublicDescription}} {{projectKey}}",
"notes": "{{repoInternalDescription}}",
"repoLayoutRef" : "{{repoTech}}-default",
"xrayIndex": true, 
"propertySets" : ["artifactory"]
}